module.exports={
    port:8585,
    db:{
        name:'node',
        user:'root',
        password:'4381545392',
        options:{
            host:'localhost',
            dialect:'sqlite',
            storage:'./db.sqlite'
        }
    }
}